/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

/**
 *
 * @author USER'
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jstockbtn = new javax.swing.JButton();
        jsalesbtn = new javax.swing.JButton();
        jinvoicebtn = new javax.swing.JButton();
        jitembtn = new javax.swing.JButton();
        jorderbtn = new javax.swing.JButton();
        jcustimerbtn = new javax.swing.JButton();
        jreportbtn = new javax.swing.JButton();
        juserbtn = new javax.swing.JButton();
        jlogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 400));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255,100));

        jstockbtn.setBackground(new java.awt.Color(204, 204, 204));
        jstockbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jstockbtn.setText("Stock");
        jstockbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jstockbtnActionPerformed(evt);
            }
        });

        jsalesbtn.setBackground(new java.awt.Color(204, 204, 204));
        jsalesbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jsalesbtn.setText("Sales");
        jsalesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsalesbtnActionPerformed(evt);
            }
        });

        jinvoicebtn.setBackground(new java.awt.Color(204, 204, 204));
        jinvoicebtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jinvoicebtn.setText("Invoice");
        jinvoicebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jinvoicebtnActionPerformed(evt);
            }
        });

        jitembtn.setBackground(new java.awt.Color(204, 204, 204));
        jitembtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jitembtn.setText("Item");
        jitembtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jitembtnActionPerformed(evt);
            }
        });

        jorderbtn.setBackground(new java.awt.Color(204, 204, 204));
        jorderbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jorderbtn.setText("Order");
        jorderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jorderbtnActionPerformed(evt);
            }
        });

        jcustimerbtn.setBackground(new java.awt.Color(204, 204, 204));
        jcustimerbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcustimerbtn.setText("Customer");
        jcustimerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcustimerbtnActionPerformed(evt);
            }
        });

        jreportbtn.setBackground(new java.awt.Color(204, 204, 204));
        jreportbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jreportbtn.setText("Reports");
        jreportbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jreportbtnActionPerformed(evt);
            }
        });

        juserbtn.setBackground(new java.awt.Color(204, 204, 204));
        juserbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        juserbtn.setText("Users");
        juserbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juserbtnActionPerformed(evt);
            }
        });

        jlogout.setBackground(new java.awt.Color(204, 204, 204));
        jlogout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlogout.setText("Logout");
        jlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(juserbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jreportbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcustimerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jinvoicebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jstockbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jitembtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsalesbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jorderbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jitembtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jstockbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jsalesbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jorderbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jinvoicebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jcustimerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jreportbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(juserbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Book Shop");

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(181, 181, 181)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(752, 752, 752))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcustimerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcustimerbtnActionPerformed
        // TODO add your handling code here:
        customer cust=new customer();
        cust.setVisible(true);
        cust.setLocationRelativeTo(null);
    }//GEN-LAST:event_jcustimerbtnActionPerformed

    private void jorderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jorderbtnActionPerformed
        // TODO add your handling code here:
        order order=new order();
        order.setVisible(true);
        order.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_jorderbtnActionPerformed

    private void jinvoicebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jinvoicebtnActionPerformed
        // TODO add your handling code here:
//         invoice invoice=new invoice();
//        invoice.setVisible(true);
//        invoice.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_jinvoicebtnActionPerformed

    private void jsalesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsalesbtnActionPerformed
        // TODO add your handling code here:
        sales sales=new sales();
        sales.setVisible(true);
        sales.setLocationRelativeTo(null);
    }//GEN-LAST:event_jsalesbtnActionPerformed

    private void jitembtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jitembtnActionPerformed
        // TODO add your handling code here:
        item item=new item();
        item.setVisible(true);//display venna
        item.setLocationRelativeTo(null);//madata ganna
           // this.dispose();
    }//GEN-LAST:event_jitembtnActionPerformed

    private void jreportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jreportbtnActionPerformed
        // TODO add your handling code here:
        reports report=new reports();
        report.setVisible(true);
        report.setLocationRelativeTo(null);
      
    }//GEN-LAST:event_jreportbtnActionPerformed

    private void juserbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juserbtnActionPerformed
        // TODO add your handling code here:
        user user=new user();
        user.setVisible(true);
        user.setLocationRelativeTo(null);
    }//GEN-LAST:event_juserbtnActionPerformed

    private void jlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlogoutActionPerformed

    private void jstockbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jstockbtnActionPerformed
        // TODO add your handling code here:
        stock stock=new stock();
        stock.setVisible(true);//display venna
        stock.setLocationRelativeTo(null);//madata ganna
           // this.dispose();
    }//GEN-LAST:event_jstockbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jcustimerbtn;
    private javax.swing.JButton jinvoicebtn;
    private javax.swing.JButton jitembtn;
    private javax.swing.JButton jlogout;
    private javax.swing.JButton jorderbtn;
    private javax.swing.JButton jreportbtn;
    private javax.swing.JButton jsalesbtn;
    private javax.swing.JButton jstockbtn;
    private javax.swing.JButton juserbtn;
    // End of variables declaration//GEN-END:variables
}
