/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER'
 */
public class item extends javax.swing.JFrame {

    /**
     * Creates new form item
     */
    public item() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jhomebtn = new javax.swing.JButton();
        jstockbtn = new javax.swing.JButton();
        jitembtn = new javax.swing.JButton();
        jsalesbtn = new javax.swing.JButton();
        jorderbtn = new javax.swing.JButton();
        jinvoice = new javax.swing.JButton();
        jcustbtn = new javax.swing.JButton();
        jreportbtn = new javax.swing.JButton();
        jlogoutbtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jitemidtxt = new javax.swing.JTextField();
        jitemnametxt = new javax.swing.JTextField();
        jitemquntxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jitempricetxt = new javax.swing.JTextField();
        jitemcattxt = new javax.swing.JTextField();
        jaddbtn = new javax.swing.JButton();
        jupdate = new javax.swing.JButton();
        jdeletebtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        setName("item"); // NOI18N

        jhomebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jhomebtn.setForeground(new java.awt.Color(0, 102, 102));
        jhomebtn.setText("Home");
        jhomebtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jhomebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhomebtnActionPerformed(evt);
            }
        });

        jstockbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jstockbtn.setForeground(new java.awt.Color(0, 102, 102));
        jstockbtn.setText("Stock");
        jstockbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jstockbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jstockbtnActionPerformed(evt);
            }
        });

        jitembtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jitembtn.setForeground(new java.awt.Color(0, 102, 102));
        jitembtn.setText("Item");
        jitembtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jitembtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jitembtnActionPerformed(evt);
            }
        });

        jsalesbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jsalesbtn.setForeground(new java.awt.Color(0, 102, 102));
        jsalesbtn.setText("Sales");
        jsalesbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jsalesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsalesbtnActionPerformed(evt);
            }
        });

        jorderbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jorderbtn.setForeground(new java.awt.Color(0, 102, 102));
        jorderbtn.setText("Order");
        jorderbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jorderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jorderbtnActionPerformed(evt);
            }
        });

        jinvoice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jinvoice.setForeground(new java.awt.Color(0, 102, 102));
        jinvoice.setText("Invoice");
        jinvoice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jinvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jinvoiceActionPerformed(evt);
            }
        });

        jcustbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jcustbtn.setForeground(new java.awt.Color(0, 102, 102));
        jcustbtn.setText("Customer");
        jcustbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jcustbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcustbtnActionPerformed(evt);
            }
        });

        jreportbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jreportbtn.setForeground(new java.awt.Color(0, 102, 102));
        jreportbtn.setText("Reports");
        jreportbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jreportbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jreportbtnActionPerformed(evt);
            }
        });

        jlogoutbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlogoutbtn.setForeground(new java.awt.Color(0, 102, 102));
        jlogoutbtn.setText("Logout");
        jlogoutbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jlogoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogoutbtnActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1250, 535));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Item List");

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Iteam_ID", "Item_Name", "Item_Quntity", "Item_Price", "Item_Category"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Item_Id");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Item_Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Item_Quntity");

        jitemidtxt.setActionCommand("<Not Set>");
        jitemidtxt.setBorder(null);
        jitemidtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jitemnametxt.setBorder(null);

        jitemquntxt.setBorder(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Item_Price");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Item_Category");

        jitempricetxt.setBorder(null);

        jitemcattxt.setBorder(null);

        jaddbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jaddbtn.setText("ADD");
        jaddbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddbtnActionPerformed(evt);
            }
        });

        jupdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jupdate.setText("Update");
        jupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jupdateActionPerformed(evt);
            }
        });

        jdeletebtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jdeletebtn.setText("Delete");
        jdeletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdeletebtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Manage Item");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(46, 46, 46)
                                .addComponent(jitemquntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jdeletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jitemidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jitemnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jitemcattxt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 536, Short.MAX_VALUE)
                                        .addComponent(jupdate))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jitempricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jaddbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jitemidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jitempricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jaddbtn))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jitemnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jitemcattxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jupdate)))
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jitemquntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jdeletebtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jitemidtxt.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlogoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jreportbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jinvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcustbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jorderbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsalesbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jitembtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jstockbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jhomebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jhomebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jitembtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jstockbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jsalesbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jorderbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jinvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcustbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jreportbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlogoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel tableModel=(DefaultTableModel)jTable1.getModel();
        
        String itemid =tableModel.getValueAt(jTable1.getSelectedRow(), 0).toString();
        String itemname =tableModel.getValueAt(jTable1.getSelectedRow(), 1).toString();
        String itemqunt =tableModel.getValueAt(jTable1.getSelectedRow(), 2).toString();
        String itemprice =tableModel.getValueAt(jTable1.getSelectedRow(), 3).toString();
        String itemcat =tableModel.getValueAt(jTable1.getSelectedRow(), 4).toString();
        
        jitemidtxt.setText(itemid);
        jitemnametxt.setText(itemname);
        jitemquntxt.setText(itemqunt);
        jitempricetxt.setText(itemprice);
        jitemcattxt.setText(itemcat);
        
    }//GEN-LAST:event_jTable1MouseClicked

    
    private void jaddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddbtnActionPerformed
        // TODO add your handling code here:
        if(jitemidtxt.getText().equals("")||jitemnametxt.getText().equals("")||jitemquntxt.getText().equals("")||jitempricetxt.getText().equals("")||jitemcattxt.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter All Data");
        }else{
            String data[]={jitemidtxt.getText(),jitemnametxt.getText(),jitemquntxt.getText(),jitempricetxt.getText(),jitemcattxt.getText()};
            
            DefaultTableModel tableModel=(DefaultTableModel) jTable1.getModel();
            tableModel.addRow(data);
            
            jitemidtxt.setText("");
            jitemnametxt.setText("");
            jitemquntxt.setText("");
            jitempricetxt.setText("");
            jitemcattxt.setText("");
        }
    }//GEN-LAST:event_jaddbtnActionPerformed

    private void jupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jupdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tableModel=(DefaultTableModel)jTable1.getModel();
        
        if(jTable1.getSelectedRowCount()==1){
            String id=jitemidtxt.getText();
            String name=jitemnametxt.getText();
            String Qun=jitemquntxt.getText();
            String price=jitempricetxt.getText();
            String cat=jitemcattxt.getText();
            
            tableModel.setValueAt(id, jTable1.getSelectedRow(), 0);
            tableModel.setValueAt(name, jTable1.getSelectedRow(), 1);
            tableModel.setValueAt(Qun, jTable1.getSelectedRow(), 2);
            tableModel.setValueAt(price, jTable1.getSelectedRow(),3);
            tableModel.setValueAt(cat, jTable1.getSelectedRow(), 4);
            
            JOptionPane.showMessageDialog(this,"Update Successfully");
        }else if(jTable1.getRowCount()==0){
            JOptionPane.showMessageDialog(this, "Table Empyt");
        }else{
            JOptionPane.showMessageDialog(this, "Please select single row for update");
        }
    }//GEN-LAST:event_jupdateActionPerformed

    private void jdeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdeletebtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tableModel=(DefaultTableModel)jTable1.getModel();
        
        if(jTable1.getSelectedRow()!=-1){
            tableModel.removeRow(jTable1.getSelectedRow());
        }else if(jTable1.getSelectedRow()==0){
            JOptionPane.showMessageDialog(this, "Table is Empty");
        }else{
            JOptionPane.showMessageDialog(this, "Please select single Row for Delete");
        }
    }//GEN-LAST:event_jdeletebtnActionPerformed

    private void jitembtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jitembtnActionPerformed
        // TODO add your handling code here:
        item item=new item();
        item.setVisible(true);//display venna
        item.setLocationRelativeTo(null);//madata ganna
           // this.dispose();
    }//GEN-LAST:event_jitembtnActionPerformed

    private void jstockbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jstockbtnActionPerformed
        // TODO add your handling code here:
        stock stock=new stock();
        stock.setVisible(true);//display venna
        stock.setLocationRelativeTo(null);//madata ganna
           // this.dispose();
    }//GEN-LAST:event_jstockbtnActionPerformed

    private void jsalesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsalesbtnActionPerformed
        // TODO add your handling code here:
        sales sales=new sales();
        sales.setVisible(true);//display venna
        sales.setLocationRelativeTo(null);//madata ganna
           // this.dispose();
    }//GEN-LAST:event_jsalesbtnActionPerformed

    private void jorderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jorderbtnActionPerformed
        // TODO add your handling code here:
        order order=new order();
        order.setVisible(true);//display venna
        order.setLocationRelativeTo(null);//madata ganna
           // this.dispose();
    }//GEN-LAST:event_jorderbtnActionPerformed

    private void jcustbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcustbtnActionPerformed
        // TODO add your handling code here:
        customer cust=new customer();
        cust.setVisible(true);
        cust.setLocationRelativeTo(null);
    }//GEN-LAST:event_jcustbtnActionPerformed

    private void jreportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jreportbtnActionPerformed
        // TODO add your handling code here:
        reports report=new reports();
        report.setVisible(true);
        report.setLocationRelativeTo(null);
    }//GEN-LAST:event_jreportbtnActionPerformed

    private void jlogoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogoutbtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jlogoutbtnActionPerformed

    private void jhomebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhomebtnActionPerformed
        // TODO add your handling code here:
          home home=new home();
          home.setVisible(true);//display venna
          home.setLocationRelativeTo(null);//madata ganna
           // this.dispose();
    }//GEN-LAST:event_jhomebtnActionPerformed

    private void jinvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jinvoiceActionPerformed
        // TODO add your handling code here:
//        invoice invoice=new invoice();
//        invoice.setVisible(true);//display venna
//        invoice.setLocationRelativeTo(null);//madata ganna
        // this.dispose();
    }//GEN-LAST:event_jinvoiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new item().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jaddbtn;
    private javax.swing.JButton jcustbtn;
    private javax.swing.JButton jdeletebtn;
    private javax.swing.JButton jhomebtn;
    private javax.swing.JButton jinvoice;
    private javax.swing.JButton jitembtn;
    private javax.swing.JTextField jitemcattxt;
    private javax.swing.JTextField jitemidtxt;
    private javax.swing.JTextField jitemnametxt;
    private javax.swing.JTextField jitempricetxt;
    private javax.swing.JTextField jitemquntxt;
    private javax.swing.JButton jlogoutbtn;
    private javax.swing.JButton jorderbtn;
    private javax.swing.JButton jreportbtn;
    private javax.swing.JButton jsalesbtn;
    private javax.swing.JButton jstockbtn;
    private javax.swing.JButton jupdate;
    // End of variables declaration//GEN-END:variables
}
