/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

    import javax.swing.JOptionPane;
    import javax.swing.table.DefaultTableModel;
    import java.awt.Color;


/**
 *
 * @author USER'
 */
public class stock extends javax.swing.JFrame {

    /**
     * Creates new form stock
     */
    public stock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablestock = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtType = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtxtID = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtxtQuant = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtxtDate = new javax.swing.JTextPane();
        jbutnstockadd = new javax.swing.JButton();
        jbutnstockDelete = new javax.swing.JButton();
        jbtnstockUpdate = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jlbllogout = new javax.swing.JLabel();
        jsthome = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jstitem = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jststock = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jstsales = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jstorder = new javax.swing.JPanel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jstinvoice = new javax.swing.JPanel();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jstcust = new javax.swing.JPanel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jstreport = new javax.swing.JPanel();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Manage Stock ");

        jTablestock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sto_ID", "Stock_Type", "Stock_Quantaty", "Stock_Date"
            }
        ));
        jTablestock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablestockMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablestock);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Stock_ID");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Stock_Quantaty");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Stock_Type");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Stock_Date");

        jtxtType.setBorder(null);
        jtxtType.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(jtxtType);

        jtxtID.setBorder(null);
        jtxtID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane3.setViewportView(jtxtID);

        jtxtQuant.setBorder(null);
        jtxtQuant.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane4.setViewportView(jtxtQuant);

        jtxtDate.setBorder(null);
        jtxtDate.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane5.setViewportView(jtxtDate);

        jbutnstockadd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbutnstockadd.setForeground(new java.awt.Color(0, 102, 102));
        jbutnstockadd.setText("Add");
        jbutnstockadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutnstockaddActionPerformed(evt);
            }
        });

        jbutnstockDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbutnstockDelete.setForeground(new java.awt.Color(0, 102, 102));
        jbutnstockDelete.setText("Delete");
        jbutnstockDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutnstockDeleteActionPerformed(evt);
            }
        });

        jbtnstockUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnstockUpdate.setForeground(new java.awt.Color(0, 102, 102));
        jbtnstockUpdate.setText("Update");
        jbtnstockUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnstockUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(39, 39, 39))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(200, 200, 200)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                                                .addComponent(jbtnstockUpdate))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jbutnstockadd, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbutnstockDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(43, 43, 43)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbutnstockadd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jbtnstockUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbutnstockDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Pramudi\\prac proj\\proj\\icons8-stock1-96.png")); // NOI18N

        jlbllogout.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jlbllogout.setForeground(new java.awt.Color(255, 255, 255));
        jlbllogout.setText("Logout");

        jsthome.setBackground(new java.awt.Color(0, 102, 102));
        jsthome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jsthomeMouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Pramudi\\prac proj\\proj\\icons8-home-32.png")); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Home");

        javax.swing.GroupLayout jsthomeLayout = new javax.swing.GroupLayout(jsthome);
        jsthome.setLayout(jsthomeLayout);
        jsthomeLayout.setHorizontalGroup(
            jsthomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jsthomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jsthomeLayout.setVerticalGroup(
            jsthomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jsthomeLayout.createSequentialGroup()
                .addGroup(jsthomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jsthomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jsthomeLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jstitem.setBackground(new java.awt.Color(0, 102, 102));
        jstitem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jstitemMouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Pramudi\\prac proj\\proj\\icons8-product-48.png")); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Item");

        jststock.setBackground(new java.awt.Color(0, 102, 102));
        jststock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jststockMouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Pramudi\\prac proj\\proj\\icons8-online-shop-48.png")); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Stock");

        javax.swing.GroupLayout jststockLayout = new javax.swing.GroupLayout(jststock);
        jststock.setLayout(jststockLayout);
        jststockLayout.setHorizontalGroup(
            jststockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jststockLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jststockLayout.setVerticalGroup(
            jststockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12)
            .addGroup(jststockLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel13))
        );

        javax.swing.GroupLayout jstitemLayout = new javax.swing.GroupLayout(jstitem);
        jstitem.setLayout(jstitemLayout);
        jstitemLayout.setHorizontalGroup(
            jstitemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jststock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jstitemLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jstitemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jstitemLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator3))
                    .addGroup(jstitemLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jstitemLayout.setVerticalGroup(
            jstitemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jstitemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jstitemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jstitemLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jststock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jstsales.setBackground(new java.awt.Color(0, 102, 102));
        jstsales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jstsalesMouseClicked(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Pramudi\\prac proj\\proj\\icons8-average-price-48.png")); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Sales");

        javax.swing.GroupLayout jstsalesLayout = new javax.swing.GroupLayout(jstsales);
        jstsales.setLayout(jstsalesLayout);
        jstsalesLayout.setHorizontalGroup(
            jstsalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jstsalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jstsalesLayout.setVerticalGroup(
            jstsalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jstsalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jstsalesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel15))
        );

        jstorder.setBackground(new java.awt.Color(0, 102, 102));
        jstorder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jstorderMouseClicked(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/icons8-shopping-cart-48.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Order");

        javax.swing.GroupLayout jstorderLayout = new javax.swing.GroupLayout(jstorder);
        jstorder.setLayout(jstorderLayout);
        jstorderLayout.setHorizontalGroup(
            jstorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jstorderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jstorderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jstorderLayout.setVerticalGroup(
            jstorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jstorderLayout.createSequentialGroup()
                .addGroup(jstorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jstorderLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel17)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jstinvoice.setBackground(new java.awt.Color(0, 102, 102));
        jstinvoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jstinvoiceMouseClicked(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/icons8-invoice-30.png"))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Invoice");

        javax.swing.GroupLayout jstinvoiceLayout = new javax.swing.GroupLayout(jstinvoice);
        jstinvoice.setLayout(jstinvoiceLayout);
        jstinvoiceLayout.setHorizontalGroup(
            jstinvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jstinvoiceLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jstinvoiceLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jstinvoiceLayout.setVerticalGroup(
            jstinvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jstinvoiceLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jstinvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jstcust.setBackground(new java.awt.Color(0, 102, 102));
        jstcust.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jstcustMouseClicked(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/icons8-people-30.png"))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Customer");

        javax.swing.GroupLayout jstcustLayout = new javax.swing.GroupLayout(jstcust);
        jstcust.setLayout(jstcustLayout);
        jstcustLayout.setHorizontalGroup(
            jstcustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jstcustLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jstcustLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jstcustLayout.setVerticalGroup(
            jstcustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jstcustLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jstcustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel22))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jstreport.setBackground(new java.awt.Color(0, 102, 102));
        jstreport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jstreportMouseClicked(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/icons8-report-30.png"))); // NOI18N

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Report");

        javax.swing.GroupLayout jstreportLayout = new javax.swing.GroupLayout(jstreport);
        jstreport.setLayout(jstreportLayout);
        jstreportLayout.setHorizontalGroup(
            jstreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jstreportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jstreportLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jstreportLayout.setVerticalGroup(
            jstreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jstreportLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jstreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                .addComponent(jSeparator1)
                                .addComponent(jSeparator4)
                                .addComponent(jSeparator5)
                                .addComponent(jSeparator6)
                                .addComponent(jsthome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jstorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jstreport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jstsales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jstcust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jstinvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jstitem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jlbllogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(87, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsthome, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jstitem, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jstsales, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jstorder, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jstinvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jstcust, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jstreport, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jlbllogout)
                        .addGap(49, 49, 49))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbutnstockaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutnstockaddActionPerformed
        // TODO add your handling code here:
        if(jtxtID.getText().equals("")||jtxtType.getText().equals("")||jtxtQuant.getText().equals("")||jtxtDate.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter All Data");
        }else{
            String data[]={jtxtID.getText(),jtxtType.getText(),jtxtQuant.getText(),jtxtDate.getText()};
            
            DefaultTableModel tblModel=(DefaultTableModel)jTablestock.getModel();
            tblModel.addRow(data);
            
            jtxtID.setText("");
            jtxtType.setText("");
            jtxtQuant.setText("");
            jtxtDate.setText("");
        }
        
    }//GEN-LAST:event_jbutnstockaddActionPerformed

    private void jTablestockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablestockMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblModel=(DefaultTableModel)jTablestock.getModel();
        
        String stockID=tblModel.getValueAt(jTablestock.getSelectedRow(),0).toString();
        String stockType=tblModel.getValueAt(jTablestock.getSelectedRow(),1).toString();
        String stockQuant=tblModel.getValueAt(jTablestock.getSelectedRow(), 2).toString();
        String stockDate=tblModel.getValueAt(jTablestock.getSelectedRow(), 3).toString();
        
        jtxtID.setText(stockID);
        jtxtType.setText(stockType);
        jtxtQuant.setText(stockQuant);
        jtxtDate.setText(stockDate);
    }//GEN-LAST:event_jTablestockMouseClicked

    private void jbtnstockUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnstockUpdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblMode=(DefaultTableModel)jTablestock.getModel();
        
        if(jTablestock.getSelectedRow()==1){
            String SID=jtxtID.getText();
            String SType=jtxtType.getText();
            String SQut=jtxtQuant.getText();
            String SDate=jtxtDate.getText();
            
            tblMode.setValueAt(SID, jTablestock.getSelectedRow(), 0);
            tblMode.setValueAt(SType, jTablestock.getSelectedRow(), 1);
            tblMode.setValueAt(SQut, jTablestock.getSelectedRow(), 2);
            tblMode.setValueAt(SDate, jTablestock.getSelectedRow(), 3);
            
            
        }
    }//GEN-LAST:event_jbtnstockUpdateActionPerformed

    private void jsthomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jsthomeMouseClicked
        // TODO add your handling code here:
         home home=new home();
        home.setVisible(true);
        home.setLocationRelativeTo(null);
        
        jsthome.setBackground(Color.lightGray);
        jstitem.setBackground(new Color(0,102,102));
        jststock.setBackground(new Color(0,102,102));
        jstsales.setBackground(new Color(0,102,102));
        jstorder.setBackground(new Color(0,102,102));
        jstinvoice.setBackground(new Color(0,102,102));
        jstcust.setBackground(new Color(0,102,102));
        jstreport.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_jsthomeMouseClicked

    private void jstitemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jstitemMouseClicked
        // TODO add your handling code here:
        item item=new item();
        item.setVisible(true);
        item.setLocationRelativeTo(null);
        
        jstitem.setBackground(Color.lightGray);
        jsthome.setBackground(new Color(0,102,102));
        jststock.setBackground(new Color(0,102,102));
        jstsales.setBackground(new Color(0,102,102));
        jstorder.setBackground(new Color(0,102,102));
        jstinvoice.setBackground(new Color(0,102,102));
        jstcust.setBackground(new Color(0,102,102));
        jstreport.setBackground(new Color(0,102,102));
        
    }//GEN-LAST:event_jstitemMouseClicked

    private void jststockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jststockMouseClicked
        // TODO add your handling code here:
         stock stock =new stock();
        stock.setVisible(true);
        stock.setLocationRelativeTo(null);
        
        jststock.setBackground(Color.lightGray);
        jsthome.setBackground(new Color(0,102,102));
        jstitem.setBackground(new Color(0,102,102));
        jstsales.setBackground(new Color(0,102,102));
        jstorder.setBackground(new Color(0,102,102));
        jstinvoice.setBackground(new Color(0,102,102));
        jstcust.setBackground(new Color(0,102,102));
        jstreport.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_jststockMouseClicked

    private void jstsalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jstsalesMouseClicked
        // TODO add your handling code here:
         sales sales=new sales();
        sales.setVisible(true);
        sales.setLocationRelativeTo(null);
        
        jstsales.setBackground(Color.lightGray);
        jsthome.setBackground(new Color(0,102,102));
        jstitem.setBackground(new Color(0,102,102));
        jststock.setBackground(new Color(0,102,102));
        jstorder.setBackground(new Color(0,102,102));
        jstinvoice.setBackground(new Color(0,102,102));
        jstcust.setBackground(new Color(0,102,102));
        jstreport.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_jstsalesMouseClicked

    private void jstorderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jstorderMouseClicked
        // TODO add your handling code here:
        order order=new order();
        order.setVisible(true);
        order.setLocationRelativeTo(null);
        
        jstorder.setBackground(Color.lightGray);
        jsthome.setBackground(new Color(0,102,102));
        jstitem.setBackground(new Color(0,102,102));
        jststock.setBackground(new Color(0,102,102));
        jstsales.setBackground(new Color(0,102,102));
        jstinvoice.setBackground(new Color(0,102,102));
        jstcust.setBackground(new Color(0,102,102));
        jstreport.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_jstorderMouseClicked

    private void jstinvoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jstinvoiceMouseClicked
        // TODO add your handling code here:
//          invoice invoice=new invoice();
//        invoice.setVisible(true);
//        invoice.setLocationRelativeTo(null);
        
        jstinvoice.setBackground(Color.lightGray);
        jsthome.setBackground(new Color(0,102,102));
        jstitem.setBackground(new Color(0,102,102));
        jststock.setBackground(new Color(0,102,102));
        jstsales.setBackground(new Color(0,102,102));
        jstorder.setBackground(new Color(0,102,102));
        jstcust.setBackground(new Color(0,102,102));
        jstreport.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_jstinvoiceMouseClicked

    private void jstcustMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jstcustMouseClicked
        // TODO add your handling code here:
         customer cust=new customer();
        cust.setVisible(true);
        cust.setLocationRelativeTo(null);
        
        jstcust .setBackground(Color.lightGray);
        jsthome.setBackground(new Color(0,102,102));
        jstitem.setBackground(new Color(0,102,102));
        jststock.setBackground(new Color(0,102,102));
        jstsales.setBackground(new Color(0,102,102));
        jstorder.setBackground(new Color(0,102,102));
        jstinvoice.setBackground(new Color(0,102,102));
        jstreport.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_jstcustMouseClicked

    private void jstreportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jstreportMouseClicked
        // TODO add your handling code here:
         reports report=new reports();
        report.setVisible(true);
        report.setLocationRelativeTo(null);

        jstreport.setBackground(Color.lightGray);
        jsthome.setBackground(new Color(0,102,102));
        jstitem.setBackground(new Color(0,102,102));
        jststock.setBackground(new Color(0,102,102));
        jstsales.setBackground(new Color(0,102,102));
        jstorder.setBackground(new Color(0,102,102));
        jstinvoice.setBackground(new Color(0,102,102));
        jstcust.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_jstreportMouseClicked

    private void jbutnstockDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutnstockDeleteActionPerformed
        // TODO add your handling code here:
         DefaultTableModel tableModel=(DefaultTableModel)jTablestock.getModel();
        
        if(jTablestock.getSelectedRow()!=-1){
            tableModel.removeRow(jTablestock.getSelectedRow());
        }else if(jTablestock.getSelectedRow()==0){
            JOptionPane.showMessageDialog(this, "Table is Empty");
        }else{
            JOptionPane.showMessageDialog(this, "Please select single Row for Delete");
        }
    }//GEN-LAST:event_jbutnstockDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTablestock;
    private javax.swing.JButton jbtnstockUpdate;
    private javax.swing.JButton jbutnstockDelete;
    private javax.swing.JButton jbutnstockadd;
    private javax.swing.JLabel jlbllogout;
    private javax.swing.JPanel jstcust;
    private javax.swing.JPanel jsthome;
    private javax.swing.JPanel jstinvoice;
    private javax.swing.JPanel jstitem;
    private javax.swing.JPanel jstorder;
    private javax.swing.JPanel jstreport;
    private javax.swing.JPanel jstsales;
    private javax.swing.JPanel jststock;
    private javax.swing.JTextPane jtxtDate;
    private javax.swing.JTextPane jtxtID;
    private javax.swing.JTextPane jtxtQuant;
    private javax.swing.JTextPane jtxtType;
    // End of variables declaration//GEN-END:variables
}
